
server.port=${PORT:8080}
server.servlet.context-path=/enghub

spring.application.name=enghub

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:enghub}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:123456}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
 
# JWT Configuration
jwt.signerKey=z8N9W8p+zXQz2J0P8L3X5Y7Z1A9B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T


# CORS Configuration
allowed.origins=http://localhost:5173
